### ISSUE TITLE
Custom data?

### ISSUE THREAD

**Issue by Juuxel** [FabLabsMC/ScreenHandlers#1]
The current `fabric-containers-v0` module allows you to send any custom data in a `PacketByteBuf` to the client when a menu is constructed. However, this needs an inconvenient method of registering and opening menus, which this API avoids by using `ContainerType`.

Is there any need for custom data?

Something I've encountered is sending the position of the opened block, but that isn't usually needed. That's usually used for syncing items/energy states etc., but that is already handled by the menu automatically.

**Comment by modmuss50** [comment]
This is required IMO, it was one the main reasons the current API is like it is.

A very common use case for this is to get the BlockEntity in the client's Container. See here <https://github.com/TechReborn/TechReborn/blob/1.15/src/main/java/techreborn/client/GuiHandler.java#L68>

I have also used it to send an entity id to the client, see here <https://github.com/modmuss50/reborntrains/blob/master/src/main/java/me/modmuss50/trains/entity/LocomotiveEntity.java#L106>

Im sure there are more usecases as well, this is not something that should be lost IMO. Possibly using NBT over a packet may be a better solution?

**Comment by Juuxel** [comment]
Yeah, those are good usecases (hadn't seen any before). NBT/bytebuf doesn't really matter to me, so I think we can just use raw bytebufs because that's what's used already.
